package org.greatfree.cache.distributed;

import java.io.Serializable;

// Created: 04/28/2018, Bing Li
public class EvictedNotification<Value extends Serializable>
{
	private String key;
	private Value value;
	
	public EvictedNotification(String key, Value value)
	{
		this.key = key;
		this.value = value;
	}
	
	// The Ehcache assigns the key through the evict(String k, Value v) interface. But it usually does not make sense to the application level. So I attempt the assign the cache key to replace it since the cache key sometimes is used on the application level, e.g., the CircleTimingPageCache. In the case, the cache key is not generated by the information from the Value, i.e., TimingPage. Thus, it is required to keep the cache key in the notification. Usually, the store needs to be updated for that. 08/09/2019, Bing Li
	public String getKey()
	{
		return this.key;
	}
	
	public Value getValue()
	{
		return this.value;
	}
	
}
